Fix OIDExternalUserAgentIOSCustomBrowser on iOS 10+
openid/AppAuth-iOS pull request #871
Opened 2024-08-19 18:16 UTC by loic-sharma

[`UIApplication openURL:`](
https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl?language=objc) is deprecated and has no effect.

On iOS 10.0+, [`UIApplication openURL:options:completionHandler:`](https://developer.apple.com/documentation/uikit/uiapplication/1648685-openurl?language=objc) should be used instead.

2024-09-03 16:43 UTC, yalkhder approved these changes

2024-09-11 20:16 UTC, loic-sharma commented
@yalkhder Do you know why the [`tests / spm-build-test (pull request)`](https://github.com/openid/AppAuth-iOS/actions/runs/10458716911/job/29843889926?pr=871) check failed?

I tried the [check's steps](https://github.com/openid/AppAuth-iOS/blob/c89ed571ae140f8eb1142735e6e23d7bb8c34cb2/.github/workflows/tests.yml#L52-L61) on my machine, that passed:

<details>
<summary>`swift test` output</summary>

```
loicsharma-macbookpro:AppAuth-iOS loicsharma$ swift build
Building for debugging...
[45/45] Compiling OIDAuthorizationService+Mac.m
Build complete! (3.71s)
loicsharma-macbookpro:AppAuth-iOS loicsharma$ swift test --enable-code-coverage
warning: 'appauth-ios': found 22 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDScopesTests.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDTokenRequestTests.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDRegistrationRequestTests.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDURLQueryComponentTests.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDRPProfileCode.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDURLQueryComponentTestsIOS7.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDAuthStateTests.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDURLSessionProviderTests.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDTokenResponseTests.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/AppAuthTV/OIDTVAuthorizationRequestTests.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDServiceDiscoveryTests.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDTokenUtilitiesTests.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/AppAuthTV/OIDTVAuthorizationResponseTests.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/AppAuthTV/OIDTVTokenRequestTests.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDAuthorizationRequestTests.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDAuthorizationResponseTests.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDGrantTypesTests.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDResponseTypesTests.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDRegistrationResponseTests.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/UnitTestsInfo.plist
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDServiceConfigurationTests.m
    /Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDEndSessionRequestTests.m
Building for debugging...
/Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDTokenResponseTests.m:178:35: warning: 'archivedDataWithRootObject:' is deprecated: first deprecated in macOS 10.14 - Use +archivedDataWithRootObject:requiringSecureCoding:error: instead [-Wdeprecated-declarations]
  178 |   NSData *data = [NSKeyedArchiver archivedDataWithRootObject:response];
      |                                   ^
/Applications/Xcode_16_rc.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSKeyedArchiver.h:47:1: note: 'archivedDataWithRootObject:' has been explicitly marked deprecated here
   47 | + (NSData *)archivedDataWithRootObject:(id)rootObject API_DEPRECATED("Use +archivedDataWithRootObject:requiringSecureCoding:error: instead", macosx(10.2,10.14), ios(2.0,12.0), watchos(2.0,5.0), tvos(9.0,12.0));
      | ^
/Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDTokenResponseTests.m:179:55: warning: 'unarchiveObjectWithData:' is deprecated: first deprecated in macOS 10.14 - Use +unarchivedObjectOfClass:fromData:error: instead [-Wdeprecated-declarations]
  179 |   OIDTokenResponse *responseCopy = [NSKeyedUnarchiver unarchiveObjectWithData:data];
      |                                                       ^
/Applications/Xcode_16_rc.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSKeyedArchiver.h:154:1: note: 'unarchiveObjectWithData:' has been explicitly marked deprecated here
  154 | + (nullable id)unarchiveObjectWithData:(NSData *)data API_DEPRECATED("Use +unarchivedObjectOfClass:fromData:error: instead", macosx(10.2,10.14), ios(2.0,12.0), watchos(2.0,5.0), tvos(9.0,12.0));
      | ^
2 warnings generated.
/Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDServiceConfigurationTests.m:366:35: warning: 'archivedDataWithRootObject:' is deprecated: first deprecated in macOS 10.14 - Use +archivedDataWithRootObject:requiringSecureCoding:error: instead [-Wdeprecated-declarations]
  366 |   NSData *data = [NSKeyedArchiver archivedDataWithRootObject:configuration];
      |                                   ^
/Applications/Xcode_16_rc.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSKeyedArchiver.h:47:1: note: 'archivedDataWithRootObject:' has been explicitly marked deprecated here
   47 | + (NSData *)archivedDataWithRootObject:(id)rootObject API_DEPRECATED("Use +archivedDataWithRootObject:requiringSecureCoding:error: instead", macosx(10.2,10.14), ios(2.0,12.0), watchos(2.0,5.0), tvos(9.0,12.0));
      | ^
/Users/loicsharma/code/AppAuth-iOS/UnitTests/OIDServiceConfigurationTests.m:367:60: warning: 'unarchiveObjectWithData:' is deprecated: first deprecated in macOS 10.14 - Use +unarchivedObjectOfClass:fromData:error: instead [-Wdeprecated-declarations]
  367 |   OIDServiceConfiguration *unarchived = [NSKeyedUnarchiver unarchiveObjectWithData:data];
      |                                                            ^
/Applications/Xcode_16_rc.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSKeyedArchiver.h:154:1: note: 'unarchiveObjectWithData:' has been explicitly marked deprecated here
  154 | + (nullable id)unarchiveObjectWithData:(NSData *)data API_DEPRECATED("Use +unarchivedObjectOfClass:fromData:error: instead", macosx(10.2,10.14), ios(2.0,12.0), watchos(2.0,5.0), tvos(9.0,12.0));
      | ^
2 warnings generated.
/Users/loicsharma/code/AppAuth-iOS/UnitTests/AppAuthTV/OIDTVAuthorizationRequestTests.m:183:35: warning: 'archivedDataWithRootObject:' is deprecated: first deprecated in macOS 10.14 - Use +archivedDataWithRootObject:requiringSecureCoding:error: instead [-Wdeprecated-declarations]
  183 |   NSData *data = [NSKeyedArchiver archivedDataWithRootObject:authRequest];
      |                                   ^
/Applications/Xcode_16_rc.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSKeyedArchiver.h:47:1: note: 'archivedDataWithRootObject:' has been explicitly marked deprecated here
   47 | + (NSData *)archivedDataWithRootObject:(id)rootObject API_DEPRECATED("Use +archivedDataWithRootObject:requiringSecureCoding:error: instead", macosx(10.2,10.14), ios(2.0,12.0), watchos(2.0,5.0), tvos(9.0,12.0));
      | ^
/Users/loicsharma/code/AppAuth-iOS/UnitTests/AppAuthTV/OIDTVAuthorizationRequestTests.m:184:67: warning: 'unarchiveObjectWithData:' is deprecated: first deprecated in macOS 10.14 - Use +unarchivedObjectOfClass:fromData:error: instead [-Wdeprecated-declarations]
  184 |   OIDTVAuthorizationRequest *authRequestCopy = [NSKeyedUnarchiver unarchiveObjectWithData:data];
      |                                                                   ^
/Applications/Xcode_16_rc.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSKeyedArchiver.h:154:1: note: 'unarchiveObjectWithData:' has been explicitly marked deprecated here
  154 | + (nullable id)unarchiveObjectWithData:(NSData *)data API_DEPRECATED("Use +unarchivedObjectOfClass:fromData:error: instead", macosx(10.2,10.14), ios(2.0,12.0), watchos(2.0,5.0), tvos(9.0,12.0));
      | ^
2 warnings generated.
/Users/loicsharma/code/AppAuth-iOS/UnitTests/AppAuthTV/OIDTVTokenRequestTests.m:171:35: warning: ' [...]

2024-09-15 11:57 UTC, ankushkushwaha approved these changes

2024-09-15 12:02 UTC, ankushkushwaha requested changes
@loic-sharma thanks for this fix for OIDExternalUserAgentIOSCustomBrowser, the last check spm-build-test in github-actions  is failing. Could you please look into it?

2024-09-16 09:33 UTC, bddq approved these changes

2024-09-16 09:37 UTC, bddq commented
Please merge it as `openURL:` without params is now deprecated in iOS 18. This currently breaks the authorization flow.

2024-09-27 19:26 UTC, loic-sharma commented
@ankushkushwaha Please see my message [above](https://github.com/openid/AppAuth-iOS/pull/871#issuecomment-2344622795). The test passes locally on my machine. I can't see the CI's output, so I can't tell what's going wrong there. Would you be able to help get additional information from the CI failure?

2024-10-14 11:35 UTC, robwalkerco commented
> @ankushkushwaha Please see my message [above](https://github.com/openid/AppAuth-iOS/pull/871#issuecomment-2344622795). The test passes locally on my machine. I can't see the CI's output, so I can't tell what's going wrong there. Would you be able to help get additional information from the CI failure?

The failing test says `This request was automatically failed because there were no enabled runners online to process the request for more than 1 days.`.

You could try pushing an empty commit to get CI to run again.

2024-10-14 11:50 UTC, robwalkerco commented
> You could try pushing an empty commit to get CI to run again.

Or you could try updating the MacOS version at https://github.com/openid/AppAuth-iOS/blob/c89ed571ae140f8eb1142735e6e23d7bb8c34cb2/.github/workflows/tests.yml#L53C4-L53C22 @loic-sharma 

As MacOS 11 runners [are no longer available on GitHub](https://github.com/actions/runner-images/tree/main/images/macos), then the test will never pass 😢

2024-10-18 23:21 UTC, loic-sharma commented
@robwalkerco @ankushkushwaha Thanks for sharing the CI output! I've updated the `spm-build-test` workflow to use `macos-12`, please approve the CI checks again?

2024-10-19 07:48 UTC, brnnmrls commented
> @robwalkerco @ankushkushwaha Thanks for sharing the CI output! I've updated the `spm-build-test` workflow to use `macos-12`.
> 
> Could you run the CI checks again please? :)

Hi everyone! I have PR #879 approved and soon to be merged in so this should resolve the failing check. There seemed to be a failing codecov issue upon updating the macos runner. @loic-sharma I'll rerun the checks once that PR is merged in.

2024-10-21 17:59 UTC, brnnmrls commented
@loic-sharma, do you mind updating your branch with main again to take in the changes?

2024-10-21 19:36 UTC, loic-sharma commented
@brnnmrls thanks for the ping - I've rebased my branch!

2024-10-21 20:55 UTC, merged

2024-10-28 08:49 UTC, robwalkerco commented
@brnnmrls will there be a new release soon with this fix?

2024-11-04 08:24 UTC, bddq commented
@brnnmrls Any news about releasing a new package version with that work? Thanks

2024-11-19 02:39 UTC, brnnmrls commented
Hi everyone, we expect this to be released by the end of this week. I'll keep y'all posted if things change.

2024-11-22 18:08 UTC, brnnmrls commented
Update: I ran into some issues with testing so I'll be releasing this early next week. Apologies for the delay!

2024-11-26 17:48 UTC, brnnmrls commented
Update: It's been released under 1.7.6!

2024-11-27 01:36 UTC, intellitour commented
Seems like iOS problem: https://forums.developer.apple.com/forums/thread/764468